apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 10.0.2.6
    path: /jenkins-pv
