apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector: 
    app: jenkins-master
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000
  
---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  selector: 
    app: jenkins-master
  type: ClusterIP  
  ports:
    - port: 50000
      targetPort: 50000
