---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-config
  namespace: metallb
spec:
  addresses:
  - 192.168.244.20-192.168.244.40
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-config
  namespace: metallb
spec:
  ipAddressPools:
    - metallb-config
